### ISSUE TITLE
已经有了更加完整的翻译版本，建议不要再做重复的工作了

### ISSUE THREAD

**Issue by LiYing2010** [T-miracle/kotlin-docs-cn#3]
我做的翻译版本在这里
https://kotlin.liying-cn.net/docs/reference_zh/about_translation.html

欢迎提出你的建议

**Comment by T-miracle** [comment]
> 我做的翻译版本在这里 https://kotlin.liying-cn.net/docs/reference_zh/about_translation.html
> 
> 欢迎提出你的建议

感谢建议，但是我的考虑就是想在翻译的过程中顺带学习一下，了解一下语言的最新消息之类的，并且样式美化方面向官方靠齐一下，主要是当前太多中文翻译有是有，就是页面样式显得有点不够官方😂
